# Generated by Django 3.0 on 2019-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_blog', models.CharField(max_length=300)),
                ('tanggal', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=10)),
                ('judul_blog', models.CharField(max_length=50)),
                ('paragraph_blog', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_mentee', models.CharField(max_length=300)),
                ('nama_mentee', models.CharField(max_length=30)),
                ('testimoni_mentee', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_mentor', models.CharField(max_length=300)),
                ('nama_mentor', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=50)),
                ('testimoni_mentor', models.CharField(max_length=300)),
            ],
        ),
    ]
